#define	REMOVE_CALENDAR

#define DEFAULT_CLOCK_TIME_SEC          10
#define DEFAULT_TEMPERATURE_TIME_SEC    6
#define DEFAULT_HUMMIDITY_TIME_SEC      5
#define DEFAULT_HC595_INTENSITY         5
#ifndef REMOVE_CALENDAR             
#define DEFAULT_DATE_TIME_SEC           8
#endif